# Generated by Django 4.2.7 on 2026-10-08 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('SUPERSEDED', 'Superseded')], default='UPLOADED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, choices=[('CLEAR', 'Clear'), ('ACCEPTABLE', 'Acceptable'), ('POOR', 'Poor Quality')], max_length=20, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_original', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PASSPORT', 'Passport'), ('NID', 'National ID'), ('PHOTO', 'Photo'), ('CV', 'CV'), ('BIRTH_CERT', 'Birth Certificate'), ('EDU_CERT', 'Educational Certificate'), ('EXP_CERT', 'Experience Certificate'), ('POLICE_CLEAR', 'Police Clearance'), ('MEDICAL_CERT', 'Medical Certificate'), ('TRAINING_CERT', 'Training Certificate'), ('CONTRACT', 'Contract'), ('VISA', 'Visa'), ('EMBASSY_DOC', 'Embassy Document'), ('CLEARANCE', 'Clearance'), ('TICKET', 'Ticket'), ('OTHER', 'Other')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('expirable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassportScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New Scan'), ('PROCESSING', 'Processing'), ('EXTRACTED', 'Extracted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('mrz_data', models.TextField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_number_confidence', models.FloatField(default=0)),
                ('surname_confidence', models.FloatField(default=0)),
                ('given_name_confidence', models.FloatField(default=0)),
                ('date_of_birth_confidence', models.FloatField(default=0)),
                ('expiry_date_confidence', models.FloatField(default=0)),
                ('mrz_valid', models.BooleanField(default=False)),
                ('all_fields_confident', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport_scan', to='candidates.candidate')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport_scan', to='documents.document')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['candidate', 'document_type'], name='documents_d_candida_08591b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx'),
        ),
    ]
