# Generated by Django 4.2.7 on 2026-10-07 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('area_country', models.CharField(blank=True, max_length=100, null=True)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('surname', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('mobile', models.CharField(db_index=True, max_length=20, unique=True)),
                ('alternative_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('upazila', models.CharField(blank=True, max_length=100, null=True)),
                ('nid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('passport_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('passport_issue_date', models.DateField()),
                ('passport_expiry_date', models.DateField()),
                ('passport_issuing_country', models.CharField(max_length=100)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('preferred_country', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_position', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, default='Manual', max_length=100, null=True)),
                ('current_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('PROCESSING', 'Processing'), ('UNAVAILABLE', 'Unavailable'), ('DEPLOYED', 'Deployed'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], default='AVAILABLE', max_length=20)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='candidates.agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_created', to=settings.AUTH_USER_MODEL)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='candidates.recruiter')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['passport_number'], name='candidates__passpor_84d93d_idx'), models.Index(fields=['mobile'], name='candidates__mobile_e2e5b0_idx'), models.Index(fields=['full_name'], name='candidates__full_na_67928d_idx'), models.Index(fields=['current_status'], name='candidates__current_7db15e_idx')],
            },
        ),
    ]
