# Generated by Django 4.2.7 on 2026-10-07 15:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_terms', models.CharField(default='NET-30', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('salary_period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('filled_count', models.IntegerField(default=0)),
                ('age_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18)])),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('ANY', 'Any'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ANY', max_length=10)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('languages', models.TextField(blank=True, null=True)),
                ('certification', models.TextField(blank=True, null=True)),
                ('passport_validity_months', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('accommodation', models.CharField(blank=True, max_length=255, null=True)),
                ('food', models.CharField(blank=True, max_length=255, null=True)),
                ('transportation', models.CharField(blank=True, max_length=255, null=True)),
                ('other_benefits', models.TextField(blank=True, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('overtime_allowed', models.BooleanField(default=True)),
                ('contract_period_months', models.IntegerField(blank=True, null=True)),
                ('visa_type', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('application_deadline', models.DateField()),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ON_HOLD', 'On Hold'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.employer')),
            ],
            options={
                'ordering': ['-posting_date'],
                'indexes': [models.Index(fields=['country', 'status'], name='jobs_job_country_9664eb_idx'), models.Index(fields=['employer', 'status'], name='jobs_job_employe_9a6de3_idx')],
            },
        ),
    ]
